CREATE DATABASE IF NOT EXISTS IMPACTA_DATABASE;
USE IMPACTA_DATABASE;

CREATE TABLE IF NOT EXISTS CLIENTE (
    CLIENT_ID INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF NUMERIC(11) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL,
    CREDIT_LIMIT DECIMAL(7, 2) NOT NULL
);

INSERT INTO CLIENTE VALUES
(1, 'AULA DOCKER', '02563252244', 'São Paulo', 'SP', 100.00);